<a href="https://colab.research.google.com/github/Leandro-Bezerra-de-Carvalho/base-alunos-GENERATION-/blob/main/AprendendoETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

datas_music = '/content/playlist_hits.json'
df_playlist = pd.read_json(datas_music)

display(df_playlist.head())

,id,titulo,artista,genero,streams_milhoes,duracao_seg
0,1,Master of Puppets,Metallica,Rock,520,515
1,2,Blinding Lights,The Weeknd,Pop,3400,200
2,3,Star Wars Main Theme,John Williams,Trilha Sonora,150,320
3,4,Bohemian Rhapsody,Queen,Rock,2100,354
4,5,Levitating,Dua Lipa,Pop,1800,203

In [ ]:
#Construir uma nova coluna no df[Categoria_tamanho]
#sempre que a musica for maior que 30s é grande se não é pequena

# 1* Colocar todos os valores da coluna
list_tamanho_music = []

# 2* Transformar um coluna em lista
list_duracoes = df_playlist['duracao_seg'].tolist()

# 3* if duracao < 300 salvar na list_tamanho_musica = 'musica grande' if < 300 = 'musica curta'

for i in list_duracoes:
  if i < 300:
    list_tamanho_music.append('musica grande')
  else:
    list_tamanho_music.append('musica curta')

# 4* Create new column, so colocar o nome de ua coluna que não existe que ele cria
df_playlist['categoria_tamanho'] = list_tamanho_music

display(df_playlist)

,id,titulo,artista,genero,streams_milhoes,duracao_seg,categoria_tamanho
0,1,Master of Puppets,Metallica,Rock,520,515,musica curta
1,2,Blinding Lights,The Weeknd,Pop,3400,200,musica grande
2,3,Star Wars Main Theme,John Williams,Trilha Sonora,150,320,musica curta
3,4,Bohemian Rhapsody,Queen,Rock,2100,354,musica curta
4,5,Levitating,Dua Lipa,Pop,1800,203,musica grande
5,6,Smells Like Teen Spirit,Nirvana,Rock,1600,301,musica curta

In [ ]:
#  Tirar métricas de um datadf com .nome_metrica()

#valor medio de todos streams
media_stream = df_playlist['streams_milhoes']
display(media_stream)
display(media_stream.mean())
display(media_stream.sum())

0     520
1    3400
2     150
3    2100
4    1800
5    1600
Name: streams_milhoes, dtype: int64

np.float64(1595.0)

np.int64(9570)

In [43]:
# Criar um filtro simples
df_dados_musica_pop = df_playlist[df_playlist['genero'] == 'Pop']
display(df_dados_musica_pop)

#Total de streams
print(f'O total de streams é de: {df_playlist['streams_milhoes'].sum()}')


# Total de streams do genero rock
df_dados_musica_pop = df_playlist[df_playlist['genero'] == 'Rock']
print(f'O total de streams é de: {df_dados_musica_pop['streams_milhoes'].sum()}')

,id,titulo,artista,genero,streams_milhoes,duracao_seg,categoria_tamanho
1,2,Blinding Lights,The Weeknd,Pop,3400,200,musica grande
4,5,Levitating,Dua Lipa,Pop,1800,203,musica grande

O total de streams é de: 9570
O total de streams é de: 4220

,id,titulo,artista,genero,streams_milhoes,duracao_seg,categoria_tamanho
0,1,Master of Puppets,Metallica,Rock,520,515,musica curta
3,4,Bohemian Rhapsody,Queen,Rock,2100,354,musica curta
5,6,Smells Like Teen Spirit,Nirvana,Rock,1600,301,musica curta

In [44]:
#Filtro simples, mas com 2 criterios
filtro_trilha_pop = ['Pop', 'Trilha Sonora']

df_dados_music_trilha = df_playlist[df_playlist['genero'].isin(filtro_trilha_pop)]

display(df_dados_music_trilha)

,id,titulo,artista,genero,streams_milhoes,duracao_seg,categoria_tamanho
1,2,Blinding Lights,The Weeknd,Pop,3400,200,musica grande
2,3,Star Wars Main Theme,John Williams,Trilha Sonora,150,320,musica curta
4,5,Levitating,Dua Lipa,Pop,1800,203,musica grande